version: '2'
services:
  maria-db:
    build: ./maria-db
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
  apache-php:
    build: ./apache-php
    ports:
      - '8080:80'
    volumes:
      - ./apache-php/html:/var/www/html
    depends_on:
      - maria-db
volumes:
  db:

