version: '2'
services:
  db:
    build: ./db
    image: savacs_db
    container_name: savacs_db
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always

  web:
    build: ./web
    image: savacs_web
    container_name: savacs_web
    hostname: savacs_web
    volumes:
      - ./web/app:/var/www/app
      - contents:/var/www/contents
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
    ports:
      - 127.0.0.1:3001:80
    env_file:
      - ./conf.env
        # SAVACS_ALIAS (required)
        #   - Web Server prefix
        #     - e.g. /savacs
        # SAVACS_GLOBAL
        #   - WAN Domain
        #     - e.g. http://example.com
        # SAVACS_LOCAL
        #   - LAN Host
        #     - e.g. http://192.168.0.3
        # GLOBAL_WEBHOOK
        #   - if set this value, all clients notifications send to this uri
        #     - e.g. https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/xXxXxXxXxXxXxXxXxXxXxXxX
    depends_on:
      - db
    restart: always

volumes:
  db:
  contents:

networks:
  default:


