version: '2'
services:
  mariadb:
    build: ./maria-db
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
  apachephp:
    build: ./apache-php
    container_name: apachephp
    ports:
      - '8080:80'
    volumes:
      - ./apache-php/html:/var/www/html
    depends_on:
      - mariadb
volumes:
  db:

